FROM quay.io/fedora-ostree-desktops/silverblue:43

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/vscode.repo > /dev/null && \
    dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y && \
    dnf config-manager setopt fedora-cisco-openh264.enabled=1

RUN rpm-ostree override remove firefox firefox-langpacks && \
    rpm-ostree install code gnome-tweaks ncdu papirus-icon-theme tilix tilix-nautilus zenity

RUN ostree container commit